version: 2

jobs:

  # python3:
  build:
    working_directory: ~/colorio
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt-get update
      # don't install sympy with apt: it pulls in texlive which takes for ever
      # to download and install
      - run: apt-get install -y git python3-pip pandoc
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install .
      # lint
      - run: pylint colorio/
      - run: pylint test/*.py
      # make sure that rst converts correctly
      - run: cat README.md | sed 's_<img src="\([^"]*\)" width="\([^"]*\)">_![](\1){width="\2"}_g' > /tmp/README.md
      - run: pandoc /tmp/README.md -o README.rst
      - run: pip3 install docutils pygments
      - run: python3 setup.py check -r -s
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov colorio
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
